### create 
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Categoria 11",
    "description": "Description categoria 11",
    "products":[]

}

### update
PATCH  http://localhost:3000/categories/677b01ebd5862c0689e1990c
Content-Type: application/json

{
    "name": "Product",
    "description": "Description"
    
}

 
### Listar Todas as Categorias (List)
GET http://localhost:3000/categories

### Listar Todas as paginado
GET http://localhost:3000/categories?page=1&limit=2


### Buscar Categoria pelo ID (Get)
GET http://localhost:3000/categories/677b01e7d5862c0689e1990a

### Deletar Categoria (Delete)
DELETE http://localhost:3000/categories/677b01e7d5862c0689e1990a
 