### Criar Order (Create)
POST http://localhost:3000/orders
Content-Type: application/json

{
    "date": "2025-01-01T12:00:00.000Z",
    "total": 500.0,
    "products":["677c412b86f61c7387b74475"]
}

### Atualizar Order (Update)
PATCH http://localhost:3000/orders/677c415086f61c7387b7447d
Content-Type: application/json

{
    "date": "2025-01-06T15:30:00.000Z",
    "total": 800.99
}

### Listar Todas as Orders
GET http://localhost:3000/orders


### Listar Todas as Orders com Paginação (List)
GET http://localhost:3000/orders?limit=1&page=1

### Buscar Order pelo ID (Get)
GET http://localhost:3000/orders/677b171d75eb3fbb407c9ad5

### Deletar Order (Delete)
DELETE http://localhost:3000/orders/677b07c77cc14212feba7193
