
### create 
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product a",
    "description": "Description of Product a",
    "price": 100,
    "imageUrl": "https://example.com/image.jpg",
    "categories" : []
}

### update 
PATCH http://localhost:3000/products/677b044b9254bec94d816acf
Content-Type: application/json

{
    "name": "John Doe updated",
    "description": "suer222@email.com",
    "price": 50
}

### list 
GET http://localhost:3000/products


### list 
GET http://localhost:3000/products?limit=2&page=2


### get 
GET http://localhost:3000/products/677b16ed75eb3fbb407c9ace


### delete 
DELETE http://localhost:3000/products/677b0d22fcad7c8660010a76